name: looklabs
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  easy_stepper: ^0.9.1
  flutter:
    sdk: flutter
  flutter_inset_box_shadow: ^1.0.8
  flutter_inset_shadow: ^2.0.3
  flutter_steps: ^1.0.5
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
