name: looklabs
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.5+1
  easy_stepper: ^0.9.1
  flutter_steps: ^1.0.5
  flutter_inset_shadow: ^2.0.3  # keep only this
  flutter_svg: ^2.2.3
  syncfusion_flutter_charts: ^32.1.19
  percent_indicator: ^4.2.5
  flutter_spinkit: ^5.2.2
  google_fonts: ^6.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/subscription/
    - assets/
    - assets/bottomIcon/
    - assets/Icon/
    - assets/splash/

  fonts:
    - family: Raleway
      fonts:
        - asset: assets/Raleway/static/Raleway-Bold.ttf
        - asset: assets/Raleway/static/Raleway-Light.ttf
        - asset: assets/Raleway/static/Raleway-Medium.ttf
        - asset: assets/Raleway/static/Raleway-Regular.ttf
        - asset: assets/Raleway/static/Raleway-SemiBold.ttf
